### ISSUE TITLE
Crashing at startup

### ISSUE THREAD

**Issue by TheFou** [themartorana/MultiFirefox#12]
Hi,
I was using MFF for some time, since the end of FF classic extensions actually, to gradually upgrade my profiles while extensions became webextensions.
Now I just migrated my last profile to the latest firefox, so I deleted the old FF v56 from /Applications, keeping only the v63. I also renamed some profiles (They all work using profile manager).
Then I launched MFF, it crashed.
I deleted everything I found in ~/Library named "*multifirefox*", then tried again : crash.
I duplicated FF in /Applications, so that I have 2 of them : crash.
*(Note : I'd like to keep using MFF for profile management, as it is easier than launching the profile manager or using the about:profiles page, without having to keep 2 FF in /Applications, if it still is a requirement as it seems to be according to INSTALL.txt)*
Any idea how I can make it work again ? Nothing changed on my computer apart from what I described above. In fact, I used it maybe 10 minutes before migrating my profile, so I'm sure that something I described here is the source of the issue.
If you need any information / test, just tell me. I'm on macOS 10.13.6.
I attached a crash report, if that can help you.

Also, in your README you state that there is a 2.4.0, but on your website the latest version is 2.3.3.
Thanks for your help.

[MultiFirefox_2018-10-29-034913_DjeMacPro.crash.zip](https://github.com/themartorana/MultiFirefox/files/2523596/MultiFirefox_2018-10-29-034913_DjeMacPro.crash.zip)

**Comment by themartorana** [comment]
Hi - thanks for the report. I haven't updated MFF in years, and may not get around to looking at this for a little while - just want to be open about this.

I did just get a new PR in that I merged, so I should look at building this again. It just may take a minute.

Thanks!

**Comment by RAMilewski** [comment]
I'm having a similar problem.  It crashes on start-up on my Macbook Pro running 10.14.2. There are several versions of Firefox in the Applications folder; FF, FF Developer Edition, FF Beta, and FF Nightly.
The crash report says: 
> Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArray0 objectAtIndex:]: index 0 beyond bounds for empty NSArray'

It works fine on my iMac running 10.13.6     My C programming skills are almost non-existent, but I'll try building 2.4.0 in X-Code and report back here if I get it to compile.

**Comment by themartorana** [comment]
This _may_ be an issue with sandboxing on MacOS. We're not asking for FS permissions (or adhering to any new MacOS requirements at all) so we may be blocked from parsing the `/Applications` directory at all.

**Comment by TheFou** [comment]
Hi!
Any chance on an update soon ?
Pleeeeease!

**Comment by RAMilewski** [comment]
Where do we send a donation to the beer fund?

**Comment by themartorana** [comment]
Hey gals/guys - so, I don't have much time to dedicate to this (read: any time) but I'll attempt to take a look soon. I apologize for this _basically_ being a dead project. I haven't done much iOS work in years and I didn't even know people still used this!  😄

**Comment by themartorana** [comment]
This is just a build with modern XCode and a change in target OS. Let me know if it still crashes, and if you can grab crash logs, please do.

https://mff_sparkle.s3.amazonaws.com/MultiFirefox_2.4.1.zip

Dave

**Comment by RAMilewski** [comment]
Tested on High Sierra 10.13.6 and Mojave 10.14.3.   Works fine on both!

THANK YOU DAVE!

**Comment by themartorana** [comment]
Haha I did not expect that. 😄

I'll push out an update.
